# Generated by Django 5.1.4 on 2025-01-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_osoba_options_osoba_wlasciciel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='stanowisko',
        ),
        migrations.RemoveField(
            model_name='osoba',
            name='wlasciciel',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='pseudonim',
            new_name='nickname',
        ),
        migrations.DeleteModel(
            name='Stanowisko',
        ),
        migrations.DeleteModel(
            name='Osoba',
        ),
    ]
